### ISSUE TITLE
Use an url/file-loader for SVG's

### ISSUE THREAD

**Issue by klaasman** [kaliberjs/build#10]
Loading SVG's is currently failing due to an error presumably in ImageMagick

```
ERROR in ./foo.svg
Module build failed: Error: Command failed: identify: no decode delegate for this image format `' @ error/constitute.c/ReadImage/501.
at ChildProcess.onExit (/X/Y/Z/node_modules/gm/lib/command.js:301:17)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at maybeClose (internal/child_process.js:899:16)
    at Socket.<anonymous> (internal/child_process.js:342:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at Pipe._handle.close [as _onclose] (net.js:509:12)

**Comment by EECOLOR** [comment]
Could it be that the svg does not include the xml header?

```
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
```

If it's not that, what version of imagemagick do you have installed?

**Comment by klaasman** [comment]
Looks like that is the case 👍
