### ISSUE TITLE
TypeError: Cannot read property 'hasRuntime' of undefined

### ISSUE THREAD

**Issue by klaasman** [kaliberjs/build#138]
Reproducable on branch [error/anonymous-imports](https://github.com/kaliberjs/build/tree/error/anonymous-imports) (3fffc9d1e7862a576621eccbc4e599ecc5a38f9e) by running `yarn start` in the example-dir.

```
Unhandled rejection of:
 Promise {
  <rejected> TypeError: Cannot read property 'hasRuntime' of undefined
    at chunkAssets.(anonymous function).group.forEach.x (/x/kaliber-build/library/webpack-plugins/chunk-manifest-plugin.js:59:38)
    at Array.forEach (<anonymous>)
    at Object.keys.reduce (/x/kaliber-build/library/webpack-plugins/chunk-manifest-plugin.js:58:40)
    at Array.reduce (<anonymous>)
    at sortGroups (/x/kaliber-build/library/webpack-plugins/chunk-manifest-plugin.js:54:45)
    at compilation.hooks.additionalChunkAssets.tap.chunks (/x/kaliber-build/library/webpack-plugins/chunk-manifest-plugin.js:49:33)
    at SyncHook.eval [as call] (eval at create (/x/kaliber-build/node_modules/tapable/lib/HookCodeFactory.js:17:12), <anonymous>:12:1)
    at SyncHook.lazyCompileHook [as _call] (/x/kaliber-build/node_modules/tapable/lib/Hook.js:35:21)
    at hooks.optimizeTree.callAsync.err (/x/kaliber-build/node_modules/webpack/lib/Compilation.js:962:37)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/x/kaliber-build/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:9:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (/x/kaliber-build/node_modules/tapable/lib/Hook.js:35:21)
    at Compilation.seal (/x/kaliber-build/node_modules/webpack/lib/Compilation.js:905:27)
    at hooks.make.callAsync.err (/x/kaliber-build/node_modules/webpack/lib/Compiler.js:494:17)
    at _fn0.then._result0 (eval at create (/x/kaliber-build/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:10:1)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7) }
```

**Comment by EECOLOR** [comment]
Thanks! That made it easy to find and fix.

The problem comes up in some special situations that should not happen in a real project. Although the next version will not break on this, it is caused by a construction that does not make sense. You need to do a normal import and a dynamic import of the same library in different chunks. The imported module should be big enough to be picked up by the 'split chunks' plugin. This will make it part of the group and because of runtime chunks not having a name, it will was not handled correctly as part of the manifest.

We already ignored runtime modules themselves, but this construction brought to light a bug in the code that did not foresee the situation.

**Comment by daveykropf** [comment]
I almost made a ticket until I saw this issue was already created. Today we had this issue in our project. Good it's fixed! Otherwise I would have walked by tomorrow.
