### ISSUE TITLE
TypeError: Cannot read property 'indexOf' of undefined

### ISSUE THREAD

**Issue by daveykropf** [kaliberjs/build#145]
```
Module build failed (from ../node_modules/@kaliber/build/webpack-loaders/css-loader.js):
TypeError: Cannot read property 'indexOf' of undefined
    at /Users/dkropf/Documents/Sites/projectname/node_modules/css-declaration-sorter/src/index.js:47:47
    at /Users/dkropf/Documents/Sites/projectname/node_modules/postcss/lib/container.js:144:26
    at Root.each (/Users/dkropf/Documents/Sites/projectname/node_modules/postcss/lib/container.js:110:22)
    at Root.walk (/Users/dkropf/Documents/Sites/projectname/node_modules/postcss/lib/container.js:143:21)
    at processCss (/Users/dkropf/Documents/Sites/projectname/node_modules/css-declaration-sorter/src/index.js:41:7)
    at /Users/dkropf/Documents/Sites/projectname/node_modules/css-declaration-sorter/src/index.js:22:14
    at initializePlugin (/Users/dkropf/Documents/Sites/projectname/node_modules/cssnano/dist/index.js:35:51)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

Error is caused by css-declaration-sorter. Workaround has been created.

**Comment by daveykropf** [comment]
Created issue: https://github.com/Siilwyn/css-declaration-sorter/issues/61
