### ISSUE TITLE
Dynamic imports

### ISSUE THREAD

**Issue by klaasman** [kaliberjs/build#29]
https://webpack.js.org/guides/code-splitting/#dynamic-imports

I couldn't get it to work

```js
System.import(/* webpackChunkName: "test" */ './Test')

// error:
TypeError: Cannot read property 'universalClient' of undefined
    at chunks.forEach.chunk (/Users/klandsman/Sites/kaliber/velux/velux-project-locator/node_modules/@kaliber/build/webpack-plugins/react-universal-plugin.js:70:28)
    at Array.forEach (native)
    at Compilation.compilation.plugin.chunks (/Users/klandsman/Sites/kaliber/velux/velux-project-locator/node_modules/@kaliber/build/webpack-plugins/react-universal-plugin.js:68:18)
    at Compilation.applyPlugins1 (/Users/klandsman/Sites/kaliber/velux/velux-project-locator/node_modules/tapable/lib/Tapable.js:75:14)
    at self.applyPluginsAsync.err (/Users/klandsman/Sites/kaliber/velux/velux-project-locator/node_modules/webpack/lib/Compilation.js:645:11)
    at Compilation.applyPluginsAsyncSeries (/Users/klandsman/Sites/kaliber/velux/velux-project-locator/node_modules/tapable/lib/Tapable.js:131:46)
    at self.applyPluginsAsync.err (/Users/klandsman/Sites/kaliber/velux/velux-project-locator/node_modules/webpack/lib/Compilation.js:641:10)
    at Compilation.applyPluginsAsyncSeries (/Users/klandsman/Sites/kaliber/velux/velux-project-locator/node_modules/tapable/lib/Tapable.js:131:46)
    at sealPart2 (/Users/klandsman/Sites/kaliber/velux/velux-project-locator/node_modules/webpack/lib/Compilation.js:637:9)
    at Compilation.applyPluginsAsyncSeries (/Users/klandsman/Sites/kaliber/velux/velux-project-locator/node_modules/tapable/lib/Tapable.js:131:46)

**Comment by EECOLOR** [comment]
To fix that particular error change 

`if (entryModule.universalClient)`

into

`if (entryModule && entryModule.universalClient)`

I'm curious, what is your usecase?

**Comment by klaasman** [comment]
A single page application with two different html-entries is problematic when there's also routing in both of those entries. Paths which don't map to a file will serve one of those entries, which means that routes which are set up in the second entry, will serve the first entry.
Therefore I'd like to have a single entry with dynamic module loading, which will prevent loading unnecessary javascript.

**Comment by klaasman** [comment]
Your suggested fix has the following error in the terminal:

```
ERROR in ReferenceError: window is not defined
```

**Comment by klaasman** [comment]
When removing the if-statement [`if (source && !source.startsWith('webpack/'))`](https://github.com/kaliberjs/build/blob/master/library/lib/node-utils.js#L36):

```
ERROR in ReferenceError: window is not defined
    at webpack/bootstrap 79718ba3d2805dfd1feb:2:1
    at null:null:1
    at webpack/universalModuleDefinition:3:1
    at webpack/universalModuleDefinition:10:2

**Comment by EECOLOR** [comment]
So, in short: it's tricky: https://github.com/webpack/webpack/issues/2471#issuecomment-218674255

Webpack is not designed to work with a single configuration in both browser and nodejs. Different plugins are enabled based on the target as seen in [WebpackOptionsApply](https://github.com/webpack/webpack/blob/master/lib/WebpackOptionsApply.js#L68-L77).

The default [is 'web'](https://github.com/webpack/webpack/blob/master/lib/WebpackOptionsDefaulter.js#L17).

Most plugins installed on 'web' target will not be problem but the `JsonpTemplatePlugin` clearly can only function in a browser. It is unclear to me at this point in time when this plugin is activated, apart from the if statement `chunk.chunks.length > 0` in the hook for `bootstrap` of the `mainTemplate`.

The correct solution here (and probably a more future-proof one) would be to create a custom target that introduces a universal version of the `JsonpTemplatePlugin`. If we choose this route we also obtain the burden to keep the new target compatible with the default (`web`) target.

Another solution would be to prevent the situation (`chunks.chunks.length > 0`) from occurring. My guess is that the chunk is added as a dependency in the [ImportParserPlugin](https://github.com/webpack/webpack/blob/3acaf94473ba8abb994dfe684663162c18050462/lib/dependencies/ImportParserPlugin.js#L23).

A third, and hacky (but potentially easy) solution could be to create our own `mainTemplate` `bootstrap` plugin that adds: `if (typeof window === 'undefined') window = {}`. The problem here might be that we miss any programming errors that use the window scope in the wrong place.

**Comment by EECOLOR** [comment]
> The use of System.import in webpack did not fit the proposed spec, so it was deprecated in webpack 2.1.0-beta.28 in favor of import()

And when using `import` you would of course need to tell babel using the `babel-plugin-syntax-dynamic-import` plugin.

**Comment by EECOLOR** [comment]
Oh, won't fix the problem.

**Comment by klaasman** [comment]
Yeah, couldn't get the `import()` to work, therefore tried the `System.import()`. Weird it didn't throw an error or at least a warning, since it's deprecated.

**Comment by EECOLOR** [comment]
Indeed, I updated the branch with the new syntax
