### ISSUE TITLE
Postcss `@apply`-feature throws an error

### ISSUE THREAD

**Issue by klaasman** [kaliberjs/build#34]
It will fail with the following syntax css:
```css
:root {
  --test-apply: {
    color: orange;
  }
}

.test {
  @apply --test-apply;
}
```

Error:
```js
ERROR in Error: Module build failed: Error: Expected pseudo-class or pseudo-element
    at new error (/foo/kaliber-build/example/node_modules/@kaliber/build/node_modules/postcss-attribute-case-insensitive/node_modules/postcss-selector-parser/dist/processor.js:29:23)
    at Parser.error (/foo/kaliber-build/example/node_modules/@kaliber/build/node_modules/postcss-attribute-case-insensitive/node_modules/postcss-selector-parser/dist/parser.js:234:15)
    at Parser.pseudo (/foo/kaliber-build/example/node_modules/@kaliber/build/node_modules/postcss-attribute-case-insensitive/node_modules/postcss-selector-parser/dist/parser.js:336:25)
    at Parser.parse (/foo/kaliber-build/example/node_modules/@kaliber/build/node_modules/postcss-attribute-case-insensitive/node_modules/postcss-selector-parser/dist/parser.js:551:22)
    at Parser.loop (/foo/kaliber-build/example/node_modules/@kaliber/build/node_modules/postcss-attribute-case-insensitive/node_modules/postcss-selector-parser/dist/parser.js:519:18)
    at new Parser (/foo/kaliber-build/example/node_modules/@kaliber/build/node_modules/postcss-attribute-case-insensitive/node_modules/postcss-selector-parser/dist/parser.js:104:21)
    at Processor.process (/foo/kaliber-build/example/node_modules/@kaliber/build/node_modules/postcss-attribute-case-insensitive/node_modules/postcss-selector-parser/dist/processor.js:26:21)
    at /foo/kaliber-build/example/node_modules/@kaliber/build/node_modules/postcss-attribute-case-insensitive/dist/index.js:107:68
    at /foo/kaliber-build/example/node_modules/@kaliber/build/node_modules/postcss/lib/container.js:241:28
    at /foo/kaliber-build/example/node_modules/@kaliber/build/node_modules/postcss/lib/container.js:148:26

**Comment by klaasman** [comment]
This fix seems to work: https://github.com/react-toolbox/react-toolbox/issues/1223#issuecomment-277976522
