### ISSUE TITLE
Build watch crashes some times

### ISSUE THREAD

**Issue by larsvankleef** [kaliberjs/build#98]
Some times when i do something wrong the build processes stops with a exit code of 1.

## log
```
Waiting for file changes...

events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at exports._errnoException (util.js:1020:11)
    at WriteWrap.afterWrite (net.js:800:14)
error Command failed with exit code 1.
ERROR: "watch" exited with 1.
error Command failed with exit code 1.
```

**Comment by EECOLOR** [comment]
hmm, tricky. It could be related to this: https://github.com/nodejs/node/issues/13204

**Comment by larsvankleef** [comment]
Got this error when making errors in css and quickly press save in the editor after each other.

**Comment by EECOLOR** [comment]
@larsvankleef can you reproduce the error by pressing save often?

**Comment by larsvankleef** [comment]
Yes, pressing the save button repeatedly was one way to crash the build tool and get this error. But i can't do it on purpose now.
